
import Util.Util;
import View.Gerente.FuncionarioInt;
import View.Gerente.GerenteInt;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author info206
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        loginInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Sair = new javax.swing.JButton();
        acessar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        senhaInput = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        cargoInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText(" Login:");

        loginInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginInputActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha:");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        acessar.setText("Acessar");
        acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarActionPerformed(evt);
            }
        });

        limpar.setText("Cancelar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        senhaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaInputActionPerformed(evt);
            }
        });

        jLabel4.setText("Cargo:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vhs_Clipart_Free.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acessar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cargoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel2)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(senhaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginInput, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loginInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sair)
                    .addComponent(limpar)
                    .addComponent(acessar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginInputActionPerformed
   // if (login.getText().equals("gerente") && (senha.getText().equals("1234")));
    //.showMessageDialog(null,"seja bem vindo"+login);
    }//GEN-LAST:event_loginInputActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
     System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarActionPerformed
        try {   

            
        Util util = new Util(); //inicializando minha classe q faz conexão com banco de dados  
        Connection conexao = util.conecta(); //faz a conexão com banco
        Statement statement = conexao.createStatement();//usa da conexão para pegar a credencial para acesso ao banco
       String sql = "SELECT * FROM Funcionario "/*WHERE login like '" + loginInput + "' AND senha like '" + senhaInput + /*"'  AND cargo_trabalho like '" + cargo +"'"*/; //Consulta SQL 
       ResultSet result = statement.executeQuery(sql);//executa a consulta SQL e agora retoena valores, por isso ResultSet
       result.first(); 
             if (loginInput.getText().equals(result.getString("login")) && senhaInput.getText().equals(result.getString("senha")) && cargoInput.getText().equals(result.getString("cargo"))){

                 
                switch (cargoInput.getText()) {
                    case "gerente":
                        //chamar tela gerente aki
                        this.dispose();
                        new GerenteInt().setVisible(true);
                        break;
                    case "funcionario":
                        //chamar tela funcionario
                        this.dispose();
                        new FuncionarioInt().setVisible(true);
                        break;
                    default:
                        JOptionPane.showMessageDialog (null,"Permissão negada ");
                        break;
                }
             }
                else{
                  JOptionPane.showMessageDialog (null,"Permissão negada ");
             }
            
         
       
       //Funcionario l = null;  //declaração de variavel  funcionario
        //while (result.next()) {
          //  l = new Funcionario(result.getString("cargo_trabalho"), result.getString("login"),result.getString("senha"));// inicializa funcionario
        //}
        
        

            //LoginContoler lgC = new LoginContoler();
            //Funcionario fLogado = lgC.autentica(cargoIput.getText(),loginInput.getText(), senhaInput.getSelectedText());
       

            }                
                
          //  JOptionPane.showMessageDialog(null,"seja bem vindo"+ login.getText());

            // mecher aki
            //}
            // } 
                    
        //EVENTO QUE FAZ O CONTROLE DE LOGIN
             /*LoginContoler lgC = new LoginContoler();
            Funcionario fLogado = lgC.autentica(loginInput.getText(), senhaInput.getSelectedText());

                
             if (.getText().equals("") || senhaInput.getText().equals(""))// se login e senha em branco
                 JOptionPane.showMessageDialog(null,"Campos login e senha são obrigatórios");//mensagem

             else //senao
             {

               try
               {

                String sql = "select * from Funcionario where login like '"
                + loginInput.getText()+"' and senha like '"+ senhaInput.getText() +"'";
                rs = Util.getConexao().executeQuery(sql);// exexuta a varialvel sql acima


                   if(rs.first())// conecta e busca o primeiro registro igual e compara se for certo entra senao da erro no CATCH
                   {
                    JOptionPane.showMessageDialog(null,"Login Efetuado com Sucesso!");
                     controla = rs.getInt("TIPO_ACESSO"); 


                       if (controla==1) // TIPO DE ACESSO DO ADMINISTRADOR
                       {
                       new T_PRINCIPAL().setVisible(true);// chama o formulario principal ao conectar

                       T_PRINCIPAL.mnpesquisa.setVisible(false); //esconde os menus do professor
                       T_PRINCIPAL.mnrelatorio.setEnabled(false) ;

                       //   principal.menu_avaliacao.setVisible(false);
                     dispose();// fecha o formulario de login ao entrar no principal
                       }


                       else if (controla==2) // TIPO DE ACESSO DE PROFESSORES
                         { 
                             new T_PRINCIPAL().setVisible(true);// chama o formulario principal ao conectar

                             T_PRINCIPAL.mnpesquisa.setVisible(true); 
                             dispose();// fecha o formulario de login ao entrar no principal

                       } 
                   }
                   else{
                        JOptionPane.showMessageDialog(null, "Dados incoretos.");
                        loginTxt.requestFocus();
                       }

                       }

                       catch (SQLException erro)
                       {
                 JOptionPane.showMessageDialog(null, "Problemas de conexão com a base de dados");

               }*/
             
         catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
         }


        
    }//GEN-LAST:event_acessarActionPerformed
    
    


    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
       loginInput.setText("");
       senhaInput.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void senhaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton acessar;
    private javax.swing.JTextField cargoInput;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField loginInput;
    private javax.swing.JPasswordField senhaInput;
    // End of variables declaration//GEN-END:variables
}
